### ISSUE TITLE
This is regarding source code.

### ISSUE THREAD

**Issue by badripatro** [liu-ziyuan-math/spectral_operator_learning#1]
Hi,
Could you please share the source code for the paper?
The current link does not have a source code.
Thanks and regards.

**Comment by liu-ziyuan-math** [comment]
We were working on more numerical experiments and sadly the computation resources are limited.
Most of the code is available now and the dataset (kind of large) will also be given once we find a good way of uploading it. Sorry for the delay.

**Comment by marvingabler** [comment]
Thanks for this & great work by the way!

**Comment by liu-ziyuan-math** [comment]
> Thanks for this & great work by the way!

Thanks & enjoy :)

**Comment by liu-ziyuan-math** [comment]
@marvingabler @badripatro The datasets are also uploaded so I'm going to close the issue. Have a good day!
